typography_spectrum: 0.6308708572010556
color:
  brandStrength: 0.9221814390219343
  lightness: 0.6105745100097196
  saturation: 0.15053068761492497
  rhythmicContrast: 0.2889224442231036
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
github: true
layout_spectrum: 0.8451501659021741
author:
  name: Doing Entertainment Negligence NPO © 2018 All Rights Reserved
  email: ambassadorofstylejr@gmail.com
  url: 'http://dentv.org'
logo: null
name: DOING ENTERTAINMENT NEGLIGENCE
url: 'https://dentv.org'
navigation:
  - name: Home
    url: 'http://dentv.org'
    type: external
  - name: Contact
    id: 5a924824-5e72-4ca9-a342-b7a907d000aa
    type: content
  - name: Donate
    id: d11d80ea-6be9-414c-bd70-d807a1a36b70
    type: content
  - name: About
    id: 5660331f-53d9-4940-a72e-851f49af2a22
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0bdcf6de-2405-4efb-90b0-0f08fbe07859.png
title: ''
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/6d9d9070-65f6-4d21-832c-0fda466816ce.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/6d9d9070-65f6-4d21-832c-0fda466816ce.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose: []
