typography_spectrum: 0.6308708572010556
color:
  brandStrength: 0.9221814390219343
  lightness: 0.6105745100097196
  saturation: 0.15053068761492497
  rhythmicContrast: 0.2889224442231036
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
github: true
layout_spectrum: 0.8451501659021741
author:
  name: >-
    Negligent TV DBA DEN is an affiliate of Ambassadors of Style Productions ©
    2016 All Rights Reserved
  email: ambassadorofstylejr@gmail.com
  url: 'http://aostyle.org'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fe354317-c3f5-42eb-9868-7bb3e2676180.png
name: DEN
navigation:
  - name: Apprenticeship Program
    id: d5fda4df-fe39-4402-8b95-6316846d2816
    type: content
  - name: Classes
    id: 7067a2d7-0f7c-4ec4-a0af-3af49b118b36
    type: content
  - name: About Us
    id: 8d463e5d-7511-4d85-90e4-4acff6bb4f04
    type: content
  - name: Contact
    id: 5a924824-5e72-4ca9-a342-b7a907d000aa
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5393dbff-d74b-44e2-ae90-7a709088e3af.png
title: ''
content: []
description: ''
purpose: []
