typography_spectrum: 0.6308708572010556
color:
  brandStrength: 0.9221814390219343
  lightness: 0.6105745100097196
  saturation: 0.15053068761492497
  rhythmicContrast: 0.2889224442231036
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
github: true
layout_spectrum: 0.8451501659021741
author:
  name: >-
    Forward TV is an affiliate of Ambassadors of Style Productions © 2016 All
    Rights Reserved
  email: ambassadorofstylejr@gmail.com
  url: 'http://aostyle.org'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9ab35366-ebce-498c-ba23-3f14224661a1.png
name: FWD TV
url: 'http://fwdtv.org'
navigation:
  - name: Apprenticeship Program
    id: 1cee4537-e9c6-49c2-b92f-46e24bdb71d1
    type: content
  - name: Home
    url: 'http://fwdtv.org'
    type: external
  - name: Register Now!
    url: 'https://dentv.typeform.com/to/GSLANq'
    type: external
  - name: About Us
    id: 16c8715c-ddf5-45ff-90f1-503032ce4d5b
    type: content
  - name: Contact
    id: 5a924824-5e72-4ca9-a342-b7a907d000aa
    type: content
  - name: Donate
    id: d11d80ea-6be9-414c-bd70-d807a1a36b70
    type: content
favicon: null
title: ''
content: []
description: ''
purpose: []
